name: Update gist
on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: yarn install
      - name: Update gist
        uses: ./
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 04f72b81edfc1fdb77c616d5223ddf9b
          USER_ID: 1755813132
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
